### ISSUE TITLE
Method not implemented XView3Dataset class

### ISSUE THREAD

**Issue by william-zhang-ml** [DIUx-xView/xview3-reference#2]
Class constructor calls get_label_map() method that is not implemented in the class.

**Comment by jdunnmon** [comment]
@william-zhang-ml this was caused by a recent modification -- we're in the process of updating to fix this.  For now, use the v1.0 tagged release, will update this when fixed.

**Comment by jdunnmon** [comment]
@william-zhang-ml should be fixed by #3 -- reopen if you still have an issue
